'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CalendarDays, CheckCircle2, Clock3, MapPin, Star } from 'lucide-react';
import { Lab } from '@/lib/types';

const slots=['08:00 AM','09:00 AM','10:30 AM','11:30 AM','01:00 PM','02:00 PM','03:30 PM','04:30 PM','05:30 PM','06:30 PM'];
function isoDate(d:Date){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
export function BookingClient({lab}:{lab:Lab}){
  const router=useRouter();
  const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);return d;}),[]);
  const [date,setDate]=useState(isoDate(days[0])); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [slot,setSlot]=useState(''); const [taken,setTaken]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{setSlot('');fetch(`/api/bookings/availability?labId=${encodeURIComponent(lab.id)}&date=${date}`).then(r=>r.json()).then(j=>setTaken(j.taken||[])).catch(()=>setTaken([]));},[date,lab.id]);
  async function book(){setError('');if(!name.trim())return setError('Enter the report/test name.');if(!slot)return setError('Choose an available time slot.');setLoading(true);const res=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lab_id:lab.id,report_name:name.trim(),report_description:description.trim(),booking_date:date,time_slot:slot})});const json=await res.json();setLoading(false);if(!res.ok)return setError(json.error||'Could not complete booking.');
    if(json.booking?.id?.startsWith?.('demo-')){
      const current=JSON.parse(localStorage.getItem('mitjayn-demo-bookings')||'[]');
      localStorage.setItem('mitjayn-demo-bookings',JSON.stringify([...current,{...json.booking,lab_name:lab.name,profile_id:'demo',created_at:new Date().toISOString()}]));
    }
    setDone(true);}
  if(done)return <div className="card mx-auto max-w-2xl p-8 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-mint text-moss"><CheckCircle2 size={30}/></div><h1 className="mt-5 text-3xl font-semibold">Appointment booked</h1><p className="mt-2 text-black/50">{name} at {lab.name} on {new Date(date+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})} at {slot}.</p><div className="mt-6 flex justify-center gap-3"><button className="btn-primary" onClick={()=>router.push('/dashboard#bookings')}>View dashboard</button><button className="btn-secondary" onClick={()=>{setDone(false);setName('');setDescription('');setSlot('')}}>Book another</button></div></div>;
  return <div className="mx-auto max-w-4xl"><section className="card p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-moss">Booking</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">{lab.name}</h1><p className="mt-2 flex items-center gap-2 text-sm text-black/45"><MapPin size={15}/>{lab.address}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-mint px-3 py-2 text-sm font-semibold text-moss"><Star size={15} className="fill-current"/> {Number(lab.rating).toFixed(1)}</span></div></section><section className="mt-5 card p-5 sm:p-7"><div className="flex items-center gap-2"><CalendarDays size={19} className="text-moss"/><h2 className="font-semibold">Choose date</h2></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{days.map(d=>{const key=isoDate(d),active=key===date;return <button key={key} onClick={()=>setDate(key)} className={`min-w-20 rounded-2xl border px-3 py-3 text-center ${active?'border-ink bg-ink text-white':'border-black/10 bg-white'}`}><span className="block text-xs opacity-60">{d.toLocaleDateString(undefined,{weekday:'short'})}</span><span className="mt-1 block text-lg font-semibold">{d.getDate()}</span></button>})}</div><div className="mt-7 grid gap-4"><label><span className="label">Report name</span><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Dengue NS1 antigen"/></label><label><span className="label">Report description</span><textarea className="input min-h-28 resize-y" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Reason for test or any details for the lab"/></label></div><div className="mt-7 flex items-center gap-2"><Clock3 size={19} className="text-moss"/><h2 className="font-semibold">Available time slots</h2></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{slots.map(s=>{const disabled=taken.includes(s);return <button key={s} disabled={disabled} onClick={()=>setSlot(s)} className={`rounded-2xl border px-3 py-3 text-sm font-semibold ${disabled?'cursor-not-allowed border-black/5 bg-black/5 text-black/25':slot===s?'border-ink bg-ink text-white':'border-black/10 hover:border-moss'}`}>{s}</button>})}</div>{error&&<div className="mt-5 rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<button onClick={book} disabled={loading} className="btn-primary mt-6 w-full sm:w-auto">{loading?'Booking…':'Book appointment'}</button></section></div>;
}
