'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Crosshair, List, Map, MapPin, Plus, Search, Star } from 'lucide-react';
import { Lab } from '@/lib/types';

function distance(a:{lat:number;lon:number},b:Lab){const R=6371;const dLat=(b.latitude-a.lat)*Math.PI/180;const dLon=(b.longitude-a.lon)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.latitude*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
export function LabsClient({initialLabs}:{initialLabs:Lab[]}){
  const [labs,setLabs]=useState(initialLabs); const [q,setQ]=useState(''); const [coords,setCoords]=useState<{lat:number;lon:number}|null>(null); const [locMsg,setLocMsg]=useState(''); const [view,setView]=useState<'list'|'map'>('list');
  const filtered=useMemo(()=>labs.filter(l=>`${l.name} ${l.address} ${l.postal_code} covid-19 monkeypox dengue malaria swine flu`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>coords?distance(coords,a)-distance(coords,b):b.rating-a.rating),[labs,q,coords]);
  const favorites=filtered.filter(l=>l.is_favorite), rest=filtered.filter(l=>!l.is_favorite);
  async function toggleFavorite(id:string){setLabs(ls=>ls.map(l=>l.id===id?{...l,is_favorite:!l.is_favorite}:l)); const res=await fetch('/api/favorites',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lab_id:id})}); if(!res.ok)setLabs(ls=>ls.map(l=>l.id===id?{...l,is_favorite:!l.is_favorite}:l));}
  function locate(){if(!navigator.geolocation){setLocMsg('Location is not supported in this browser.');return;}setLocMsg('Locating…');navigator.geolocation.getCurrentPosition(p=>{setCoords({lat:p.coords.latitude,lon:p.coords.longitude});setLocMsg('Sorted by distance from you.');},()=>setLocMsg('Location permission was denied. Showing top-rated labs instead.'));}
  const LabRow=({lab}:{lab:Lab})=><div className="card flex items-center gap-4 p-4 sm:p-5"><button onClick={()=>toggleFavorite(lab.id)} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-sand" aria-label="Favorite lab"><Star size={18} className={lab.is_favorite?'fill-amber-400 text-amber-400':'text-black/35'}/></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold">{lab.name}</h3><span className="rounded-full bg-mint px-2 py-1 text-[11px] font-semibold text-moss">★ {Number(lab.rating).toFixed(1)}</span></div><p className="mt-1 truncate text-sm text-black/45">{lab.address}</p>{coords&&<p className="mt-1 text-xs font-medium text-moss">{distance(coords,lab).toFixed(1)} km away</p>}</div><Link aria-label="Book lab" href={lab.branch_count?`/labs/${lab.id}/branches`:`/labs/${lab.id}/book`} className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-ink text-white"><Plus size={19}/></Link></div>;
  return <div className="mx-auto max-w-6xl"><header><p className="text-sm font-medium text-moss">Partner network</p><h1 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">Find a diagnostic lab</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-black/45">Search by lab, address or postal code, then choose a branch and an available slot.</p></header><div className="mt-7 card p-4"><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 text-black/35" size={18}/><input className="input !pl-11" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by address / postal code / report name"/></div><button onClick={locate} className="btn-secondary"><Crosshair size={17}/> Use location</button><div className="flex rounded-2xl bg-sand p-1"><button onClick={()=>setView('list')} className={`rounded-xl p-2.5 ${view==='list'?'bg-white shadow-sm':''}`}><List size={17}/></button><button onClick={()=>setView('map')} className={`rounded-xl p-2.5 ${view==='map'?'bg-white shadow-sm':''}`}><Map size={17}/></button></div></div>{locMsg&&<p className="mt-3 px-1 text-xs text-black/45">{locMsg}</p>}</div>{view==='map'&&<div className="mt-5 overflow-hidden rounded-3xl border border-black/5 bg-[#e9eee7] p-5 sm:p-8"><div className="relative h-64 rounded-2xl bg-[radial-gradient(circle_at_20%_30%,white_0_2px,transparent_3px),linear-gradient(115deg,transparent_35%,rgba(46,111,87,.12)_36%_39%,transparent_40%_60%,rgba(46,111,87,.12)_61%_64%,transparent_65%)]"><div className="absolute left-[48%] top-[42%] grid h-12 w-12 place-items-center rounded-full bg-ink text-white shadow"><MapPin/></div><p className="absolute bottom-4 left-4 rounded-xl bg-white/90 px-3 py-2 text-xs text-black/55">Prototype map view · switch to list to choose a lab</p></div></div>}
  {view==='list'&&<><section className="mt-8"><h2 className="text-lg font-semibold">List of favorite labs</h2><div className="mt-3 grid gap-3">{favorites.length?favorites.map(l=><LabRow key={l.id} lab={l}/>):<div className="rounded-2xl border border-dashed border-black/10 p-6 text-sm text-black/40">Star a lab to keep it here.</div>}</div></section><section className="mt-8"><h2 className="text-lg font-semibold">List of all labs</h2><div className="mt-3 grid gap-3">{rest.map(l=><LabRow key={l.id} lab={l}/>)}</div>{filtered.length===0&&<div className="py-10 text-center text-sm text-black/40">No labs match this search.</div>}</section></>}</div>;
}
